### PR TITLE
Vue 2

### PR DESCRIPTION
**Pull request by cpb8010**
So obviously this is huge, with lots of little changes I'll try to detail.
# General Migration Changes
1. The most common change is html template formatting. No more triple bracket syntax, instead I moved most text into computed properties with v-html attributes. I also autoformatted most of the files I edited, so the indentation was often changed to be more regular. I also tried to remove some now unnecessary escaping, which impacted the translation files.

2. The next biggest is the removal of $mountTo/thenable. Vue's appendTo was removed entirely. The old dialog flow didn't play well with event propagation(no $broadcast), so I transitioned all the modals to components with a global event hub. I don't love this design, but it was simple enough to work.

3. The last general change was basically a rename with an additional indentation. The ready hook was removed, and its replacement is mounted + nextTick. I didn't look if the components really needed the $el and just put everything into this format just in case.

Please try this out, as I only have intermediate experience with actually using Twine and don't know if I broke any edge case. While I'd like this to be seamless it might be safe to make it minor version bump, what's your preference here?
Also I setup a CI system, so I'd love if you wanted to turn that on for PRs and general maintainability.

------
## More Detailed notes
I'll try to outline where I did changes beyond what the vue migration tool suggested, where functionality may be different.

### Codemirror
This component was mutating props to communicate with it's parent component, which produces an error in Vue 2. I moved this internal sync mechanism entirely to the parent class. Saving text on mount could then be an easy 'undo' functionality if desired.

### Data to Props
There were a number of components that were passed information via data directly. Vue2 doesn't support this, so I've made much more extensive use of props. This is most common now in the modal-dialogs.

### Zoom-Transition

This was a non-functional component and didn't play well without mountTo/thenable, so I dropped it entirely. It was only used on 1 component, so I didn't put much effort into figuring out what went wrong.

### App-state
The import behaved differently in tests, so I changed it to be a little lazier. I assume this was a change in order of initiation or import or something, but it was easy enough to just add the () to make it clear something was happening on import.

### Style changes

At one point I ran prettier on this in an attempt to meet the eslint config, only to find that a large portion of the code doesn't match. I didn't notice this at first, and attempted to undo it in parts near the end to reduce the final diff. There are still sections that are nothing but formatting/style changes, but I'm hesitant to revert any file that might have had a small syntax change as well. If this was a serious concern I might try to write a script and rebase out the offending commit.

### CODE REVIEW

**Comment by cpb8010** [comment]
I tried to go through all the dialogs manually and catch what I saw were crash bugs. I put up this latest version on https://valorstories.com/twinejs/index.html


Now the only thing I haven't looked at all is the nw.js stuff, but I didn't touch it either, so hopefully it plays along.

**Comment by cpb8010** [comment]
Updated to beta1. Should I target this develop?

**Comment by cpb8010** [comment]
Fewer whitespace changes ;)

Just let me know when to merge or something big like the Jest change lands
in develop.

**Comment by cpb8010** [comment]
♥️prettier!

**Comment by kfirzuberi** [comment]
Hi. is there a plan to merge this and upgrade to vue 2+?

**Comment by cpb8010** [comment]
@klembot You should be able to sign up for free and then connect this repo as a GitHub app. Then it will either build on the next push to the branch or you can kick a run off manually within CircleCI.

I also looked into the free tier of Azure pipelines for free Windows and OSX builds (if you wanted to automate the electron-build step for publishing), but I haven't fully tested that yet.

The circleci steps now are just internal consistency checks: the run commands will fail the build if the last command returns a non-zero exit code.

**Pull request merged**
