### PR TITLE
Updated Harlowe to 3.3.5.

### PR DESCRIPTION
**Pull request by webbedspace**
This just has a performance fix, but I'd like it out before March.

### CODE REVIEW

**Comment by webbedspace** [comment]
Hrmm… I just want it to be over and done with, and not get gummed up like 3.3.4 was… but if you pinky-promise this update of yours will be only March, I guess I can wait a couple more weeks.

**Comment by zeltas** [comment]
Hi Klem, I would very much like to do what you do. Code Twine 2. Assume I know nothing. Do you have any screen videos or instruction notes/pdf, examples or self-made tutorials on writing/programming Twine code that you could share or better yet, a manual on **How To Make Twine 2**?

Thanks

**Comment by webbedspace** [comment]
↑ Please ban this person for spam

**Comment by zeltas** [comment]
My sincere apology to any offended as I do understand. Like Twine, Harlowe was much appreciated as hard earned respect is built over time, but easily erased with a single comment. No need, I will ban myself.

**Comment by webbedspace** [comment]
There are a high volume of spam comments going around GitHub recently, and I have little patience for this sort of thing recently, especially when they blatantly take a thread off topic.

**Pull request merged**
