### PR TITLE
Adding New Line Characters

### PR DESCRIPTION
**Pull request by kendagriff**
My team has begun poking around in Twine's source for ways to make it a bit more friendly to a team. One issue we're seeing is that if you place a Twine story in Git, it's nearly impossible to manage merge conflicts.

This commit adds some new line characters that _starts_ to make it manageable. Any interest or thoughts in something like this?

### CODE REVIEW

**Comment by kendagriff** [comment]
The % increase will be proportional to the number of nodes, right? About 29B (measured by the total increase in characters) per node.

An HTML beautifier would add even more, I presume, however, I personally like the tradeoff because an HTML file can always be minified later.

**Comment by kendagriff** [comment]
I'd be open to adding a PR for a beautifier if you like. Haven't used one before, but I'm sure I can manage...

**Comment by Erdromian** [comment]
We were able to run js-beautify on the html files in a pre-commit hook. https://newfivefour.com/beautify-format-html-javascript-command-line-npm.html

```
#!/bin/sh

for value in $(git diff --name-only --cached | grep ".*\.html")
do
  cat $value | js-beautify -f - --type html -o $value
  git add $value
done
```

**Comment by Erdromian** [comment]
Update: js-beautify 'formats' the content inside the <tw-passagedata> elements, which messes with the white space inside the passages.  Looking for an alternative formatter

**Comment by Erdromian** [comment]
Our new script looks like:
```
#!/bin/sh
#.git/hooks/pre-commit

IFS=$'\n'
for value in $(git diff --name-only --cached | grep ".*\.html")
do
  cat $value | js-beautify -f - --type html -T tw-passagedata -o $value
  git add $value
done
unset IFS
```

The option `-T tw-passagedata` prevents the unwanted formatting from happening.
An unrelated fix is `IFS=$'\n'`, to allow our for loop to handle file names with spaces in them.

**Pull request closed without merging**
