### PR TITLE
fix blank lines added to styles and scripts sections on import, see #505

### PR DESCRIPTION
**Pull request by hogart**
+minor speedup (not that it really matters in this case, but join is faster for this operation, see https://jsbench.me/ouk13kh80v/1)

### CODE REVIEW

**Comment by hogart** [comment]
I work on games from 2 computers and oftenly with co-author, using VCS for sharing. Each import adds empty lines to script and styles, which I have to remove manually when commiting changes.

**Comment by tmedwards** [comment]
Did you test that?  Because, unless I'm having a senior moment, the implicit `.toString()` of the element nodes in question, via the `.join()`, is going to be `[object HTML…Element]` rather than the `.textContent` you want.  It seems like they should be some thing like:

```javascript
Array.from(storyEl.querySelectorAll(selectors.…))
	.map(el => el.textContent)
	.join('\n'),
```

**Comment by hogart** [comment]
Sorry, didn't test this because build was broken for me.
Updated as per your sugestion.

**Comment by hogart** [comment]
And updated tests too.

**Pull request merged**
