### PR TITLE
Add docker support

### PR DESCRIPTION
**Pull request by guysoft**
Added docker support, had to add --host 0.0.0.0 so it would be served outside the container.

You can run try it out by running:
```
docker run -p 8080:8080 --name twinejs guysoft/twinejs
```
I made an automated build on docker hub so any new commit would update the image automatically.

Also would gladly help you set up official builds from docker hub.

### CODE REVIEW

**Comment by guysoft** [comment]
If you tell me where the stories are saved, I can put them in a docker volume.

**Comment by guysoft** [comment]
It means you can deploy twinejs as a service without worrying about how the
dependencies work. And a more secure manner.

Moreover you can integrate it with an existing docker service. I used it to
deploy the cointiner behind a reverse proxy which also handles https.
See:
https://github.com/jwilder/nginx-proxy

You can see it at:
https://twinejs.gnethomelinux.com/

**Comment by cpb8010** [comment]
I think a Docker image could help contributors! But as is, I don't think it's useful.

Twine is deployed as a static site (the dist folder). You shouldn't ever expose the service that runs with ```npm start``` as the [webpack-serve](https://github.com/webpack-contrib/webpack-serve) is only for debugging and is very, very slow (and deprecated now that I checked it!). Maybe a docker image could be helpful for those publishing a twine game, where it runs something like apache or ngix to serve single static HTML file produced by Twine.


For development, this image is far too many things in it. The benefit of docker is that you don't need to bring a ton of unnecessary dependencies onto your machine and the image built here could be much slimmer if it used something like: https://github.com/mhart/alpine-node or https://github.com/nodejs/docker-node, because it has no other dependencies. Because this is a pure JavaScript project, the only real benefit I could see would be avoiding installing node and electron deps (which are minimal).

If you want to set up some automated builds, I could use some help in making a comprehensive CI pipeline that builds, tests, packages, and publishes.

**Comment by guysoft** [comment]
@cpb8010 Are you saying this should be merged or does it need a change that blocks it?

**Comment by guysoft** [comment]
Was it merged?

**Pull request closed without merging**
