### PR TITLE
Add Catalan translation.

### PR DESCRIPTION
**Pull request by jmallach**

### CODE REVIEW

**Comment by jmallach** [comment]
@klembot, I wonder if you're considering this PR for the next release? If so I might try to get the new translatable strings into the new po, after the fixes in 78cff86.

**Comment by jmallach** [comment]
Hey @klembot, I just rebased stuff to current master.

**Comment by miquelangelfuentes** [comment]
Do you need any help with the Catalan translation? 

I would like to offer my help in that regard if necessary!

**Comment by jmallach** [comment]
The translation is complete, using a PO file generated with @cpb8010's patch to support template literals.

For now, there's not a lot to be done, besides of course reviewing the current translation. Thanks!

**Comment by miquelangelfuentes** [comment]
Moltíssimes gràcies!! It will be very useful!!

**Pull request merged**
